// Code generated by Fern. DO NOT EDIT.

package organization_identity_providers_domains_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	myorganization "github.com/auth0/myorganization-go"
	client "github.com/auth0/myorganization-go/client"
	option "github.com/auth0/myorganization-go/option"
	require "github.com/stretchr/testify/require"
	http "net/http"
	os "os"
	testing "testing"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WiremockAdminURL := "http://localhost:" + wiremockPort + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestOrganizationIdentityProvidersDomainsCreateWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewWithOptions(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &myorganization.CreateIdpDomainRequestContent{
		Domain: "my-domain.com",
	}
	_, invocationErr := client.Organization.IdentityProviders.Domains.Create(
		context.TODO(),
		"idp_id",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestOrganizationIdentityProvidersDomainsCreateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestOrganizationIdentityProvidersDomainsCreateWithWireMock", "POST", "/identity-providers/idp_id/domains", nil, 1)
}

func TestOrganizationIdentityProvidersDomainsDeleteWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewWithOptions(
		option.WithBaseURL(WireMockBaseURL),
	)
	invocationErr := client.Organization.IdentityProviders.Domains.Delete(
		context.TODO(),
		"idp_id",
		"domain",
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestOrganizationIdentityProvidersDomainsDeleteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestOrganizationIdentityProvidersDomainsDeleteWithWireMock", "DELETE", "/identity-providers/idp_id/domains/domain", nil, 1)
}
