// Code generated by Fern. DO NOT EDIT.

package identityproviders

import (
	context "context"
	myorganization "github.com/auth0/myorganization-go"
	core "github.com/auth0/myorganization-go/core"
	internal "github.com/auth0/myorganization-go/internal"
	option "github.com/auth0/myorganization-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Retrieve the connection profile for the application. This will give the components all of the information they will need to be successful. The SDK provider for the components should manage fetching and caching this information for all components.
func (c *Client) Get(
	ctx context.Context,
	opts ...option.RequestOption,
) (myorganization.GetIdpConfigurationResponseContent, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
