// Code generated by Fern. DO NOT EDIT.

package client

import (
	core "github.com/auth0/myorganization-go/v2/core"
	internal "github.com/auth0/myorganization-go/v2/internal"
	option "github.com/auth0/myorganization-go/v2/option"
	client "github.com/auth0/myorganization-go/v2/organization/client"
	organizationdetails "github.com/auth0/myorganization-go/v2/organizationdetails"
)

type MyOrganization struct {
	OrganizationDetails *organizationdetails.Client
	Organization        *client.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewWithOptions(opts ...option.RequestOption) *MyOrganization {
	options := core.NewRequestOptions(opts...)
	return &MyOrganization{
		OrganizationDetails: organizationdetails.NewClient(options),
		Organization:        client.NewClient(options),
		options:             options,
		baseURL:             options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}
