// Code generated by Fern. DO NOT EDIT.

package organization_identity_providers_provisioning_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	client "github.com/auth0/myorganization-go/client"
	option "github.com/auth0/myorganization-go/option"
	require "github.com/stretchr/testify/require"
	http "net/http"
	os "os"
	testing "testing"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WiremockAdminURL := "http://localhost:" + wiremockPort + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestOrganizationIdentityProvidersProvisioningGetWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewWithOptions(
		option.WithBaseURL(WireMockBaseURL),
	)
	_, invocationErr := client.Organization.IdentityProviders.Provisioning.Get(
		context.TODO(),
		"idp_id",
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestOrganizationIdentityProvidersProvisioningGetWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestOrganizationIdentityProvidersProvisioningGetWithWireMock", "GET", "/identity-providers/idp_id/provisioning", nil, 1)
}

func TestOrganizationIdentityProvidersProvisioningCreateWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewWithOptions(
		option.WithBaseURL(WireMockBaseURL),
	)
	_, invocationErr := client.Organization.IdentityProviders.Provisioning.Create(
		context.TODO(),
		"idp_id",
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestOrganizationIdentityProvidersProvisioningCreateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestOrganizationIdentityProvidersProvisioningCreateWithWireMock", "POST", "/identity-providers/idp_id/provisioning", nil, 1)
}

func TestOrganizationIdentityProvidersProvisioningDeleteWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewWithOptions(
		option.WithBaseURL(WireMockBaseURL),
	)
	invocationErr := client.Organization.IdentityProviders.Provisioning.Delete(
		context.TODO(),
		"idp_id",
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestOrganizationIdentityProvidersProvisioningDeleteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestOrganizationIdentityProvidersProvisioningDeleteWithWireMock", "DELETE", "/identity-providers/idp_id/provisioning", nil, 1)
}

func TestOrganizationIdentityProvidersProvisioningUpdateAttributesWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewWithOptions(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := map[string]any{
		"key": "value",
	}
	_, invocationErr := client.Organization.IdentityProviders.Provisioning.UpdateAttributes(
		context.TODO(),
		"idp_id",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestOrganizationIdentityProvidersProvisioningUpdateAttributesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestOrganizationIdentityProvidersProvisioningUpdateAttributesWithWireMock", "PUT", "/identity-providers/idp_id/provisioning/update-attributes", nil, 1)
}
