// Code generated by Fern. DO NOT EDIT.

package client

import (
	context "context"
	http "net/http"

	myorganization "github.com/auth0/myorganization-go"
	core "github.com/auth0/myorganization-go/core"
	internal "github.com/auth0/myorganization-go/internal"
	option "github.com/auth0/myorganization-go/option"
	roles "github.com/auth0/myorganization-go/organization/members/roles"
)

type Client struct {
	WithRawResponse *RawClient
	Roles           *roles.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		Roles:           roles.NewClient(options),
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Retrieve a list of all members for this Organization. The `roles` field is only included for each member when the token also carries the `read:my_org:member_roles` scope; without that scope the `roles` field is omitted from the response.
func (c *Client) List(
	ctx context.Context,
	request *myorganization.ListOrganizationMembersRequestParameters,
	opts ...option.RequestOption,
) (*core.Page[*string, *myorganization.OrgMember, *myorganization.ListOrganizationMembersResponseContent], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"https://%7BTENANT%7D.auth0.com/my-org/v1",
	)
	endpointURL := baseURL + "/members"
	queryParams, err := internal.QueryValuesWithDefaults(
		request,
		map[string]any{
			"include_fields": true,
			"take":           50,
		},
	)
	if err != nil {
		return nil, err
	}
	headers := internal.MergeHeaders(
		c.options.ToHeader(),
		options.ToHeader(),
	)
	prepareCall := func(pageRequest *core.PageRequest[*string]) *internal.CallParams {
		if pageRequest.Cursor != nil {
			queryParams.Set("from", *pageRequest.Cursor)
		}
		nextURL := endpointURL
		if len(queryParams) > 0 {
			nextURL += "?" + queryParams.Encode()
		}
		return &internal.CallParams{
			URL:             nextURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        pageRequest.Response,
			ErrorDecoder:    internal.NewErrorDecoder(myorganization.ErrorCodes),
		}
	}
	readPageResponse := func(response *myorganization.ListOrganizationMembersResponseContent) *core.PageResponse[*string, *myorganization.OrgMember, *myorganization.ListOrganizationMembersResponseContent] {
		var zeroValue *string
		next := response.Next
		results := response.Members
		return &core.PageResponse[*string, *myorganization.OrgMember, *myorganization.ListOrganizationMembersResponseContent]{
			Results:  results,
			Response: response,
			Next:     next,
			Done:     next == zeroValue,
		}
	}
	pager := internal.NewCursorPager(
		c.caller,
		prepareCall,
		readPageResponse,
	)
	return pager.GetPage(ctx, request.From)
}

// Retrieve details of a member specified by user ID for this Organization.
func (c *Client) Get(
	ctx context.Context,
	userID myorganization.OrgMemberID,
	request *myorganization.GetOrganizationMemberRequestParameters,
	opts ...option.RequestOption,
) (myorganization.GetOrganizationMemberResponseContent, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		userID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
