// Code generated by Fern. DO NOT EDIT.

package organization_identity_providers_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	myorganization "github.com/auth0/myorganization-go"
	client "github.com/auth0/myorganization-go/client"
	option "github.com/auth0/myorganization-go/option"
	require "github.com/stretchr/testify/require"
	http "net/http"
	os "os"
	testing "testing"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WiremockAdminURL := "http://localhost:" + wiremockPort + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestOrganizationIdentityProvidersListWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewWithOptions(
		option.WithBaseURL(WireMockBaseURL),
	)
	_, invocationErr := client.Organization.IdentityProviders.List(
		context.TODO(),
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestOrganizationIdentityProvidersListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestOrganizationIdentityProvidersListWithWireMock", "GET", "/identity-providers", nil, 1)
}

func TestOrganizationIdentityProvidersCreateWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewWithOptions(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &myorganization.IdpKnownRequest{
		IdpAdfsRequest: &myorganization.IdpAdfsRequest{
			Name: "oidcIdp",
			Domains: []string{
				"mydomain.com",
			},
			DisplayName: myorganization.String(
				"OIDC IdP",
			),
			ShowAsButton: myorganization.Bool(
				true,
			),
			AssignMembershipOnLogin: myorganization.Bool(
				false,
			),
			IsEnabled: myorganization.Bool(
				true,
			),
			Options: &myorganization.IdpAdfsOptionsRequest{
				IdpAdfsOptionsRequestAdfsServer: &myorganization.IdpAdfsOptionsRequestAdfsServer{},
			},
		},
	}
	_, invocationErr := client.Organization.IdentityProviders.Create(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestOrganizationIdentityProvidersCreateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestOrganizationIdentityProvidersCreateWithWireMock", "POST", "/identity-providers", nil, 1)
}

func TestOrganizationIdentityProvidersGetWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewWithOptions(
		option.WithBaseURL(WireMockBaseURL),
	)
	_, invocationErr := client.Organization.IdentityProviders.Get(
		context.TODO(),
		"idp_id",
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestOrganizationIdentityProvidersGetWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestOrganizationIdentityProvidersGetWithWireMock", "GET", "/identity-providers/idp_id", nil, 1)
}

func TestOrganizationIdentityProvidersDeleteWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewWithOptions(
		option.WithBaseURL(WireMockBaseURL),
	)
	invocationErr := client.Organization.IdentityProviders.Delete(
		context.TODO(),
		"idp_id",
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestOrganizationIdentityProvidersDeleteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestOrganizationIdentityProvidersDeleteWithWireMock", "DELETE", "/identity-providers/idp_id", nil, 1)
}

func TestOrganizationIdentityProvidersUpdateWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewWithOptions(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &myorganization.IdpUpdateKnownRequest{
		IdpAdfsUpdateRequest: &myorganization.IdpAdfsUpdateRequest{
			DisplayName: myorganization.String(
				"OIDC IdP",
			),
			ShowAsButton: myorganization.Bool(
				true,
			),
			AssignMembershipOnLogin: myorganization.Bool(
				false,
			),
			IsEnabled: myorganization.Bool(
				true,
			),
			Options: &myorganization.IdpAdfsOptionsRequest{
				IdpAdfsOptionsRequestAdfsServer: &myorganization.IdpAdfsOptionsRequestAdfsServer{},
			},
		},
	}
	_, invocationErr := client.Organization.IdentityProviders.Update(
		context.TODO(),
		"idp_id",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestOrganizationIdentityProvidersUpdateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestOrganizationIdentityProvidersUpdateWithWireMock", "PATCH", "/identity-providers/idp_id", nil, 1)
}

func TestOrganizationIdentityProvidersUpdateAttributesWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewWithOptions(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := map[string]any{
		"key": "value",
	}
	_, invocationErr := client.Organization.IdentityProviders.UpdateAttributes(
		context.TODO(),
		"idp_id",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestOrganizationIdentityProvidersUpdateAttributesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestOrganizationIdentityProvidersUpdateAttributesWithWireMock", "PUT", "/identity-providers/idp_id/update-attributes", nil, 1)
}

func TestOrganizationIdentityProvidersDetachWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewWithOptions(
		option.WithBaseURL(WireMockBaseURL),
	)
	invocationErr := client.Organization.IdentityProviders.Detach(
		context.TODO(),
		"idp_id",
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestOrganizationIdentityProvidersDetachWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestOrganizationIdentityProvidersDetachWithWireMock", "POST", "/identity-providers/idp_id/detach", nil, 1)
}
