// Code generated by Fern. DO NOT EDIT.

package userstores

import (
	context "context"

	myorganization "github.com/auth0/myorganization-go"
	core "github.com/auth0/myorganization-go/core"
	internal "github.com/auth0/myorganization-go/internal"
	option "github.com/auth0/myorganization-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Retrieve the user stores for the associated Organization.
func (c *Client) List(
	ctx context.Context,
	request *myorganization.ListOrganizationUserStoresRequestParameters,
	opts ...option.RequestOption,
) (*myorganization.ListUserStoresResponseContent, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
