// Code generated by Fern. DO NOT EDIT.

package myorganization

import (
	json "encoding/json"
	core "github.com/auth0/myorganization-go/core"
)

// Invalid request body. The message will vary depending on the cause.
type BadRequestError struct {
	*core.APIError
	Body interface{}
}

func (b *BadRequestError) UnmarshalJSON(data []byte) error {
	var body interface{}
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	b.StatusCode = 400
	b.Body = body
	return nil
}

func (b *BadRequestError) MarshalJSON() ([]byte, error) {
	return json.Marshal(b.Body)
}

func (b *BadRequestError) Unwrap() error {
	return b.APIError
}

// Domain name already exists.
type ConflictError struct {
	*core.APIError
	Body *ErrorResponseContent
}

func (c *ConflictError) UnmarshalJSON(data []byte) error {
	var body *ErrorResponseContent
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	c.StatusCode = 409
	c.Body = body
	return nil
}

func (c *ConflictError) MarshalJSON() ([]byte, error) {
	return json.Marshal(c.Body)
}

func (c *ConflictError) Unwrap() error {
	return c.APIError
}

// Insufficient scope.
type ForbiddenError struct {
	*core.APIError
	Body *ErrorResponseContent
}

func (f *ForbiddenError) UnmarshalJSON(data []byte) error {
	var body *ErrorResponseContent
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	f.StatusCode = 403
	f.Body = body
	return nil
}

func (f *ForbiddenError) MarshalJSON() ([]byte, error) {
	return json.Marshal(f.Body)
}

func (f *ForbiddenError) Unwrap() error {
	return f.APIError
}

// Organization not found.
type NotFoundError struct {
	*core.APIError
	Body *ErrorResponseContent
}

func (n *NotFoundError) UnmarshalJSON(data []byte) error {
	var body *ErrorResponseContent
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	n.StatusCode = 404
	n.Body = body
	return nil
}

func (n *NotFoundError) MarshalJSON() ([]byte, error) {
	return json.Marshal(n.Body)
}

func (n *NotFoundError) Unwrap() error {
	return n.APIError
}

// Too many requests. Check the X-RateLimit-Limit, X-RateLimit-Remaining and X-RateLimit-Reset headers.
type TooManyRequestsError struct {
	*core.APIError
	Body *ErrorResponseContent
}

func (t *TooManyRequestsError) UnmarshalJSON(data []byte) error {
	var body *ErrorResponseContent
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	t.StatusCode = 429
	t.Body = body
	return nil
}

func (t *TooManyRequestsError) MarshalJSON() ([]byte, error) {
	return json.Marshal(t.Body)
}

func (t *TooManyRequestsError) Unwrap() error {
	return t.APIError
}

// Unauthorized: token missing, invalid or expired.
type UnauthorizedError struct {
	*core.APIError
	Body *ErrorResponseContent
}

func (u *UnauthorizedError) UnmarshalJSON(data []byte) error {
	var body *ErrorResponseContent
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	u.StatusCode = 401
	u.Body = body
	return nil
}

func (u *UnauthorizedError) MarshalJSON() ([]byte, error) {
	return json.Marshal(u.Body)
}

func (u *UnauthorizedError) Unwrap() error {
	return u.APIError
}
