// Code generated by Fern. DO NOT EDIT.

package myorganization

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersOrgBranding(t *testing.T) {
	t.Run("SetLogoURL", func(t *testing.T) {
		obj := &OrgBranding{}
		var fernTestValueLogoURL *string
		obj.SetLogoURL(fernTestValueLogoURL)
		assert.Equal(t, fernTestValueLogoURL, obj.LogoURL)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetColors", func(t *testing.T) {
		obj := &OrgBranding{}
		var fernTestValueColors *OrgBrandingColors
		obj.SetColors(fernTestValueColors)
		assert.Equal(t, fernTestValueColors, obj.Colors)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersOrgBranding(t *testing.T) {
	t.Run("GetLogoURL", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &OrgBranding{}
		var value string
		obj.LogoURL = &value

		// Act & Assert
		assert.Equal(t, value, obj.GetLogoURL(), "getter should dereference and return the value")
	})

	t.Run("GetLogoURL_NilProperty", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &OrgBranding{}
		obj.LogoURL = nil
		var expectedZero string

		// Act & Assert
		assert.Equal(t, expectedZero, obj.GetLogoURL(), "getter should return zero value when property is nil")
	})

	t.Run("GetLogoURL_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *OrgBranding
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetLogoURL() // Should return zero value
	})

	t.Run("GetColors", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &OrgBranding{}
		var value OrgBrandingColors
		obj.Colors = &value

		// Act & Assert
		assert.Equal(t, value, obj.GetColors(), "getter should dereference and return the value")
	})

	t.Run("GetColors_NilProperty", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &OrgBranding{}
		obj.Colors = nil
		var expectedZero OrgBrandingColors

		// Act & Assert
		assert.Equal(t, expectedZero, obj.GetColors(), "getter should return zero value when property is nil")
	})

	t.Run("GetColors_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *OrgBranding
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetColors() // Should return zero value
	})

}

func TestSettersMarkExplicitOrgBranding(t *testing.T) {
	t.Run("SetLogoURL_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &OrgBranding{}
		var fernTestValueLogoURL *string

		// Act
		obj.SetLogoURL(fernTestValueLogoURL)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetColors_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &OrgBranding{}
		var fernTestValueColors *OrgBrandingColors

		// Act
		obj.SetColors(fernTestValueColors)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersOrgBrandingColors(t *testing.T) {
	t.Run("SetPrimary", func(t *testing.T) {
		obj := &OrgBrandingColors{}
		var fernTestValuePrimary string
		obj.SetPrimary(fernTestValuePrimary)
		assert.Equal(t, fernTestValuePrimary, obj.Primary)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPageBackground", func(t *testing.T) {
		obj := &OrgBrandingColors{}
		var fernTestValuePageBackground string
		obj.SetPageBackground(fernTestValuePageBackground)
		assert.Equal(t, fernTestValuePageBackground, obj.PageBackground)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersOrgBrandingColors(t *testing.T) {
	t.Run("GetPrimary", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &OrgBrandingColors{}
		var expected string
		obj.Primary = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetPrimary(), "getter should return the property value")
	})

	t.Run("GetPrimary_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *OrgBrandingColors
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetPrimary() // Should return zero value
	})

	t.Run("GetPageBackground", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &OrgBrandingColors{}
		var expected string
		obj.PageBackground = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetPageBackground(), "getter should return the property value")
	})

	t.Run("GetPageBackground_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *OrgBrandingColors
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetPageBackground() // Should return zero value
	})

}

func TestSettersMarkExplicitOrgBrandingColors(t *testing.T) {
	t.Run("SetPrimary_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &OrgBrandingColors{}
		var fernTestValuePrimary string

		// Act
		obj.SetPrimary(fernTestValuePrimary)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPageBackground_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &OrgBrandingColors{}
		var fernTestValuePageBackground string

		// Act
		obj.SetPageBackground(fernTestValuePageBackground)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersOrgDetails(t *testing.T) {
	t.Run("SetName", func(t *testing.T) {
		obj := &OrgDetails{}
		var fernTestValueName *string
		obj.SetName(fernTestValueName)
		assert.Equal(t, fernTestValueName, obj.Name)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDisplayName", func(t *testing.T) {
		obj := &OrgDetails{}
		var fernTestValueDisplayName *string
		obj.SetDisplayName(fernTestValueDisplayName)
		assert.Equal(t, fernTestValueDisplayName, obj.DisplayName)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetBranding", func(t *testing.T) {
		obj := &OrgDetails{}
		var fernTestValueBranding *OrgBranding
		obj.SetBranding(fernTestValueBranding)
		assert.Equal(t, fernTestValueBranding, obj.Branding)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersOrgDetails(t *testing.T) {
	t.Run("GetName", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &OrgDetails{}
		var value string
		obj.Name = &value

		// Act & Assert
		assert.Equal(t, value, obj.GetName(), "getter should dereference and return the value")
	})

	t.Run("GetName_NilProperty", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &OrgDetails{}
		obj.Name = nil
		var expectedZero string

		// Act & Assert
		assert.Equal(t, expectedZero, obj.GetName(), "getter should return zero value when property is nil")
	})

	t.Run("GetName_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *OrgDetails
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetName() // Should return zero value
	})

	t.Run("GetDisplayName", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &OrgDetails{}
		var value string
		obj.DisplayName = &value

		// Act & Assert
		assert.Equal(t, value, obj.GetDisplayName(), "getter should dereference and return the value")
	})

	t.Run("GetDisplayName_NilProperty", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &OrgDetails{}
		obj.DisplayName = nil
		var expectedZero string

		// Act & Assert
		assert.Equal(t, expectedZero, obj.GetDisplayName(), "getter should return zero value when property is nil")
	})

	t.Run("GetDisplayName_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *OrgDetails
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDisplayName() // Should return zero value
	})

	t.Run("GetBranding", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &OrgDetails{}
		var value OrgBranding
		obj.Branding = &value

		// Act & Assert
		assert.Equal(t, value, obj.GetBranding(), "getter should dereference and return the value")
	})

	t.Run("GetBranding_NilProperty", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &OrgDetails{}
		obj.Branding = nil
		var expectedZero OrgBranding

		// Act & Assert
		assert.Equal(t, expectedZero, obj.GetBranding(), "getter should return zero value when property is nil")
	})

	t.Run("GetBranding_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *OrgDetails
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetBranding() // Should return zero value
	})

}

func TestSettersMarkExplicitOrgDetails(t *testing.T) {
	t.Run("SetName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &OrgDetails{}
		var fernTestValueName *string

		// Act
		obj.SetName(fernTestValueName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDisplayName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &OrgDetails{}
		var fernTestValueDisplayName *string

		// Act
		obj.SetDisplayName(fernTestValueDisplayName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetBranding_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &OrgDetails{}
		var fernTestValueBranding *OrgBranding

		// Act
		obj.SetBranding(fernTestValueBranding)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersOrgDetailsRead(t *testing.T) {
	t.Run("SetID", func(t *testing.T) {
		obj := &OrgDetailsRead{}
		var fernTestValueID *OrgID
		obj.SetID(fernTestValueID)
		assert.Equal(t, fernTestValueID, obj.ID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetName", func(t *testing.T) {
		obj := &OrgDetailsRead{}
		var fernTestValueName *string
		obj.SetName(fernTestValueName)
		assert.Equal(t, fernTestValueName, obj.Name)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDisplayName", func(t *testing.T) {
		obj := &OrgDetailsRead{}
		var fernTestValueDisplayName *string
		obj.SetDisplayName(fernTestValueDisplayName)
		assert.Equal(t, fernTestValueDisplayName, obj.DisplayName)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetBranding", func(t *testing.T) {
		obj := &OrgDetailsRead{}
		var fernTestValueBranding *OrgBranding
		obj.SetBranding(fernTestValueBranding)
		assert.Equal(t, fernTestValueBranding, obj.Branding)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersOrgDetailsRead(t *testing.T) {
	t.Run("GetID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &OrgDetailsRead{}
		var value OrgID
		obj.ID = &value

		// Act & Assert
		assert.Equal(t, value, obj.GetID(), "getter should dereference and return the value")
	})

	t.Run("GetID_NilProperty", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &OrgDetailsRead{}
		obj.ID = nil
		var expectedZero OrgID

		// Act & Assert
		assert.Equal(t, expectedZero, obj.GetID(), "getter should return zero value when property is nil")
	})

	t.Run("GetID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *OrgDetailsRead
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetID() // Should return zero value
	})

	t.Run("GetName", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &OrgDetailsRead{}
		var value string
		obj.Name = &value

		// Act & Assert
		assert.Equal(t, value, obj.GetName(), "getter should dereference and return the value")
	})

	t.Run("GetName_NilProperty", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &OrgDetailsRead{}
		obj.Name = nil
		var expectedZero string

		// Act & Assert
		assert.Equal(t, expectedZero, obj.GetName(), "getter should return zero value when property is nil")
	})

	t.Run("GetName_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *OrgDetailsRead
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetName() // Should return zero value
	})

	t.Run("GetDisplayName", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &OrgDetailsRead{}
		var value string
		obj.DisplayName = &value

		// Act & Assert
		assert.Equal(t, value, obj.GetDisplayName(), "getter should dereference and return the value")
	})

	t.Run("GetDisplayName_NilProperty", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &OrgDetailsRead{}
		obj.DisplayName = nil
		var expectedZero string

		// Act & Assert
		assert.Equal(t, expectedZero, obj.GetDisplayName(), "getter should return zero value when property is nil")
	})

	t.Run("GetDisplayName_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *OrgDetailsRead
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDisplayName() // Should return zero value
	})

	t.Run("GetBranding", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &OrgDetailsRead{}
		var value OrgBranding
		obj.Branding = &value

		// Act & Assert
		assert.Equal(t, value, obj.GetBranding(), "getter should dereference and return the value")
	})

	t.Run("GetBranding_NilProperty", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &OrgDetailsRead{}
		obj.Branding = nil
		var expectedZero OrgBranding

		// Act & Assert
		assert.Equal(t, expectedZero, obj.GetBranding(), "getter should return zero value when property is nil")
	})

	t.Run("GetBranding_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *OrgDetailsRead
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetBranding() // Should return zero value
	})

}

func TestSettersMarkExplicitOrgDetailsRead(t *testing.T) {
	t.Run("SetID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &OrgDetailsRead{}
		var fernTestValueID *OrgID

		// Act
		obj.SetID(fernTestValueID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &OrgDetailsRead{}
		var fernTestValueName *string

		// Act
		obj.SetName(fernTestValueName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDisplayName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &OrgDetailsRead{}
		var fernTestValueDisplayName *string

		// Act
		obj.SetDisplayName(fernTestValueDisplayName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetBranding_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &OrgDetailsRead{}
		var fernTestValueBranding *OrgBranding

		// Act
		obj.SetBranding(fernTestValueBranding)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingOrgBranding(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &OrgBranding{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled OrgBranding
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj OrgBranding
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj OrgBranding
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingOrgBrandingColors(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &OrgBrandingColors{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled OrgBrandingColors
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj OrgBrandingColors
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj OrgBrandingColors
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingOrgDetails(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &OrgDetails{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled OrgDetails
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj OrgDetails
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj OrgDetails
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingOrgDetailsRead(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &OrgDetailsRead{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled OrgDetailsRead
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj OrgDetailsRead
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj OrgDetailsRead
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringOrgBranding(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &OrgBranding{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *OrgBranding
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringOrgBrandingColors(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &OrgBrandingColors{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *OrgBrandingColors
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringOrgDetails(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &OrgDetails{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *OrgDetails
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringOrgDetailsRead(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &OrgDetailsRead{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *OrgDetailsRead
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestExtraPropertiesOrgBranding(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &OrgBranding{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *OrgBranding
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesOrgBrandingColors(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &OrgBrandingColors{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *OrgBrandingColors
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesOrgDetails(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &OrgDetails{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *OrgDetails
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesOrgDetailsRead(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &OrgDetailsRead{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *OrgDetailsRead
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
