// Code generated by Fern. DO NOT EDIT.

package myorganization

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/auth0/myorganization-go/internal"
	big "math/big"
)

type GetOrganizationDetailsResponseContent = *OrgDetailsRead

// Theme defines how to style the login pages.
var (
	orgBrandingFieldLogoURL = big.NewInt(1 << 0)
	orgBrandingFieldColors  = big.NewInt(1 << 1)
)

type OrgBranding struct {
	// URL of logo to display on login page.
	LogoURL *string            `json:"logo_url,omitempty" url:"logo_url,omitempty"`
	Colors  *OrgBrandingColors `json:"colors,omitempty" url:"colors,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (o *OrgBranding) GetLogoURL() string {
	if o == nil || o.LogoURL == nil {
		return ""
	}
	return *o.LogoURL
}

func (o *OrgBranding) GetColors() OrgBrandingColors {
	if o == nil || o.Colors == nil {
		return OrgBrandingColors{}
	}
	return *o.Colors
}

func (o *OrgBranding) GetExtraProperties() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.extraProperties
}

func (o *OrgBranding) require(field *big.Int) {
	if o.explicitFields == nil {
		o.explicitFields = big.NewInt(0)
	}
	o.explicitFields.Or(o.explicitFields, field)
}

// SetLogoURL sets the LogoURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *OrgBranding) SetLogoURL(logoURL *string) {
	o.LogoURL = logoURL
	o.require(orgBrandingFieldLogoURL)
}

// SetColors sets the Colors field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *OrgBranding) SetColors(colors *OrgBrandingColors) {
	o.Colors = colors
	o.require(orgBrandingFieldColors)
}

func (o *OrgBranding) UnmarshalJSON(data []byte) error {
	type unmarshaler OrgBranding
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*o = OrgBranding(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *o)
	if err != nil {
		return err
	}
	o.extraProperties = extraProperties
	o.rawJSON = json.RawMessage(data)
	return nil
}

func (o *OrgBranding) MarshalJSON() ([]byte, error) {
	type embed OrgBranding
	var marshaler = struct {
		embed
	}{
		embed: embed(*o),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, o.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (o *OrgBranding) String() string {
	if o == nil {
		return "<nil>"
	}
	if len(o.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(o.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}

// Color scheme used to customize the login pages.
var (
	orgBrandingColorsFieldPrimary        = big.NewInt(1 << 0)
	orgBrandingColorsFieldPageBackground = big.NewInt(1 << 1)
)

type OrgBrandingColors struct {
	// HEX Color for primary elements.
	Primary string `json:"primary" url:"primary"`
	// HEX Color for background.
	PageBackground string `json:"page_background" url:"page_background"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (o *OrgBrandingColors) GetPrimary() string {
	if o == nil {
		return ""
	}
	return o.Primary
}

func (o *OrgBrandingColors) GetPageBackground() string {
	if o == nil {
		return ""
	}
	return o.PageBackground
}

func (o *OrgBrandingColors) GetExtraProperties() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.extraProperties
}

func (o *OrgBrandingColors) require(field *big.Int) {
	if o.explicitFields == nil {
		o.explicitFields = big.NewInt(0)
	}
	o.explicitFields.Or(o.explicitFields, field)
}

// SetPrimary sets the Primary field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *OrgBrandingColors) SetPrimary(primary string) {
	o.Primary = primary
	o.require(orgBrandingColorsFieldPrimary)
}

// SetPageBackground sets the PageBackground field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *OrgBrandingColors) SetPageBackground(pageBackground string) {
	o.PageBackground = pageBackground
	o.require(orgBrandingColorsFieldPageBackground)
}

func (o *OrgBrandingColors) UnmarshalJSON(data []byte) error {
	type unmarshaler OrgBrandingColors
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*o = OrgBrandingColors(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *o)
	if err != nil {
		return err
	}
	o.extraProperties = extraProperties
	o.rawJSON = json.RawMessage(data)
	return nil
}

func (o *OrgBrandingColors) MarshalJSON() ([]byte, error) {
	type embed OrgBrandingColors
	var marshaler = struct {
		embed
	}{
		embed: embed(*o),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, o.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (o *OrgBrandingColors) String() string {
	if o == nil {
		return "<nil>"
	}
	if len(o.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(o.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}

var (
	orgDetailsFieldName        = big.NewInt(1 << 0)
	orgDetailsFieldDisplayName = big.NewInt(1 << 1)
	orgDetailsFieldBranding    = big.NewInt(1 << 2)
)

type OrgDetails struct {
	// The name of this organization.
	Name *string `json:"name,omitempty" url:"name,omitempty"`
	// Friendly name of this organization.
	DisplayName *string      `json:"display_name,omitempty" url:"display_name,omitempty"`
	Branding    *OrgBranding `json:"branding,omitempty" url:"branding,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (o *OrgDetails) GetName() string {
	if o == nil || o.Name == nil {
		return ""
	}
	return *o.Name
}

func (o *OrgDetails) GetDisplayName() string {
	if o == nil || o.DisplayName == nil {
		return ""
	}
	return *o.DisplayName
}

func (o *OrgDetails) GetBranding() OrgBranding {
	if o == nil || o.Branding == nil {
		return OrgBranding{}
	}
	return *o.Branding
}

func (o *OrgDetails) GetExtraProperties() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.extraProperties
}

func (o *OrgDetails) require(field *big.Int) {
	if o.explicitFields == nil {
		o.explicitFields = big.NewInt(0)
	}
	o.explicitFields.Or(o.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *OrgDetails) SetName(name *string) {
	o.Name = name
	o.require(orgDetailsFieldName)
}

// SetDisplayName sets the DisplayName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *OrgDetails) SetDisplayName(displayName *string) {
	o.DisplayName = displayName
	o.require(orgDetailsFieldDisplayName)
}

// SetBranding sets the Branding field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *OrgDetails) SetBranding(branding *OrgBranding) {
	o.Branding = branding
	o.require(orgDetailsFieldBranding)
}

func (o *OrgDetails) UnmarshalJSON(data []byte) error {
	type unmarshaler OrgDetails
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*o = OrgDetails(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *o)
	if err != nil {
		return err
	}
	o.extraProperties = extraProperties
	o.rawJSON = json.RawMessage(data)
	return nil
}

func (o *OrgDetails) MarshalJSON() ([]byte, error) {
	type embed OrgDetails
	var marshaler = struct {
		embed
	}{
		embed: embed(*o),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, o.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (o *OrgDetails) String() string {
	if o == nil {
		return "<nil>"
	}
	if len(o.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(o.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}

var (
	orgDetailsReadFieldID          = big.NewInt(1 << 0)
	orgDetailsReadFieldName        = big.NewInt(1 << 1)
	orgDetailsReadFieldDisplayName = big.NewInt(1 << 2)
	orgDetailsReadFieldBranding    = big.NewInt(1 << 3)
)

type OrgDetailsRead struct {
	ID *OrgID `json:"id,omitempty" url:"id,omitempty"`
	// The name of this organization.
	Name *string `json:"name,omitempty" url:"name,omitempty"`
	// Friendly name of this organization.
	DisplayName *string      `json:"display_name,omitempty" url:"display_name,omitempty"`
	Branding    *OrgBranding `json:"branding,omitempty" url:"branding,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (o *OrgDetailsRead) GetID() OrgID {
	if o == nil || o.ID == nil {
		return ""
	}
	return *o.ID
}

func (o *OrgDetailsRead) GetName() string {
	if o == nil || o.Name == nil {
		return ""
	}
	return *o.Name
}

func (o *OrgDetailsRead) GetDisplayName() string {
	if o == nil || o.DisplayName == nil {
		return ""
	}
	return *o.DisplayName
}

func (o *OrgDetailsRead) GetBranding() OrgBranding {
	if o == nil || o.Branding == nil {
		return OrgBranding{}
	}
	return *o.Branding
}

func (o *OrgDetailsRead) GetExtraProperties() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.extraProperties
}

func (o *OrgDetailsRead) require(field *big.Int) {
	if o.explicitFields == nil {
		o.explicitFields = big.NewInt(0)
	}
	o.explicitFields.Or(o.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *OrgDetailsRead) SetID(id *OrgID) {
	o.ID = id
	o.require(orgDetailsReadFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *OrgDetailsRead) SetName(name *string) {
	o.Name = name
	o.require(orgDetailsReadFieldName)
}

// SetDisplayName sets the DisplayName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *OrgDetailsRead) SetDisplayName(displayName *string) {
	o.DisplayName = displayName
	o.require(orgDetailsReadFieldDisplayName)
}

// SetBranding sets the Branding field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *OrgDetailsRead) SetBranding(branding *OrgBranding) {
	o.Branding = branding
	o.require(orgDetailsReadFieldBranding)
}

func (o *OrgDetailsRead) UnmarshalJSON(data []byte) error {
	type unmarshaler OrgDetailsRead
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*o = OrgDetailsRead(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *o)
	if err != nil {
		return err
	}
	o.extraProperties = extraProperties
	o.rawJSON = json.RawMessage(data)
	return nil
}

func (o *OrgDetailsRead) MarshalJSON() ([]byte, error) {
	type embed OrgDetailsRead
	var marshaler = struct {
		embed
	}{
		embed: embed(*o),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, o.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (o *OrgDetailsRead) String() string {
	if o == nil {
		return "<nil>"
	}
	if len(o.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(o.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}

type UpdateOrganizationDetailsRequestContent = *OrgDetails

type UpdateOrganizationDetailsResponseContent = *OrgDetailsRead
