// Code generated by Fern. DO NOT EDIT.

package myorganization

import (
	json "encoding/json"
	internal "github.com/auth0/myorganization-go/internal"
	big "math/big"
)

var (
	createOrganizationDomainRequestContentFieldDomain = big.NewInt(1 << 0)
)

type CreateOrganizationDomainRequestContent struct {
	Domain OrgDomainName `json:"domain" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateOrganizationDomainRequestContent) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetDomain sets the Domain field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateOrganizationDomainRequestContent) SetDomain(domain OrgDomainName) {
	c.Domain = domain
	c.require(createOrganizationDomainRequestContentFieldDomain)
}

func (c *CreateOrganizationDomainRequestContent) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateOrganizationDomainRequestContent
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateOrganizationDomainRequestContent(body)
	return nil
}

func (c *CreateOrganizationDomainRequestContent) MarshalJSON() ([]byte, error) {
	type embed CreateOrganizationDomainRequestContent
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	createIdpProvisioningSCIMTokenRequestContentFieldTokenLifetime = big.NewInt(1 << 0)
)

type CreateIdpProvisioningSCIMTokenRequestContent struct {
	// Lifetime of the token in seconds. Do not set for non-expiring tokens.
	TokenLifetime *int `json:"token_lifetime,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateIdpProvisioningSCIMTokenRequestContent) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetTokenLifetime sets the TokenLifetime field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateIdpProvisioningSCIMTokenRequestContent) SetTokenLifetime(tokenLifetime *int) {
	c.TokenLifetime = tokenLifetime
	c.require(createIdpProvisioningSCIMTokenRequestContentFieldTokenLifetime)
}

func (c *CreateIdpProvisioningSCIMTokenRequestContent) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateIdpProvisioningSCIMTokenRequestContent
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateIdpProvisioningSCIMTokenRequestContent(body)
	return nil
}

func (c *CreateIdpProvisioningSCIMTokenRequestContent) MarshalJSON() ([]byte, error) {
	type embed CreateIdpProvisioningSCIMTokenRequestContent
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	createIdpDomainRequestContentFieldDomain = big.NewInt(1 << 0)
)

type CreateIdpDomainRequestContent struct {
	Domain OrgDomainName `json:"domain" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateIdpDomainRequestContent) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetDomain sets the Domain field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateIdpDomainRequestContent) SetDomain(domain OrgDomainName) {
	c.Domain = domain
	c.require(createIdpDomainRequestContentFieldDomain)
}

func (c *CreateIdpDomainRequestContent) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateIdpDomainRequestContent
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateIdpDomainRequestContent(body)
	return nil
}

func (c *CreateIdpDomainRequestContent) MarshalJSON() ([]byte, error) {
	type embed CreateIdpDomainRequestContent
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	listOrganizationDomainsRequestParametersFieldFrom = big.NewInt(1 << 0)
	listOrganizationDomainsRequestParametersFieldTake = big.NewInt(1 << 1)
)

type ListOrganizationDomainsRequestParameters struct {
	// An optional cursor from which to start the selection (exclusive).
	From *string `json:"-" url:"from,omitempty"`
	// Number of results per page. Defaults to 50.
	Take *int `json:"-" url:"take,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListOrganizationDomainsRequestParameters) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetFrom sets the From field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListOrganizationDomainsRequestParameters) SetFrom(from *string) {
	l.From = from
	l.require(listOrganizationDomainsRequestParametersFieldFrom)
}

// SetTake sets the Take field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListOrganizationDomainsRequestParameters) SetTake(take *int) {
	l.Take = take
	l.require(listOrganizationDomainsRequestParametersFieldTake)
}
