// Code generated by Fern. DO NOT EDIT.

package myorganization

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersCreateOrganizationDomainRequestContent(t *testing.T) {
	t.Run("SetDomain", func(t *testing.T) {
		obj := &CreateOrganizationDomainRequestContent{}
		var fernTestValueDomain OrgDomainName
		obj.SetDomain(fernTestValueDomain)
		assert.Equal(t, fernTestValueDomain, obj.Domain)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitCreateOrganizationDomainRequestContent(t *testing.T) {
	t.Run("SetDomain_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateOrganizationDomainRequestContent{}
		var fernTestValueDomain OrgDomainName

		// Act
		obj.SetDomain(fernTestValueDomain)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersCreateIdpDomainRequestContent(t *testing.T) {
	t.Run("SetDomain", func(t *testing.T) {
		obj := &CreateIdpDomainRequestContent{}
		var fernTestValueDomain OrgDomainName
		obj.SetDomain(fernTestValueDomain)
		assert.Equal(t, fernTestValueDomain, obj.Domain)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitCreateIdpDomainRequestContent(t *testing.T) {
	t.Run("SetDomain_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateIdpDomainRequestContent{}
		var fernTestValueDomain OrgDomainName

		// Act
		obj.SetDomain(fernTestValueDomain)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersCreateIdpProvisioningSCIMTokenRequestContent(t *testing.T) {
	t.Run("SetTokenLifetime", func(t *testing.T) {
		obj := &CreateIdpProvisioningSCIMTokenRequestContent{}
		var fernTestValueTokenLifetime *int
		obj.SetTokenLifetime(fernTestValueTokenLifetime)
		assert.Equal(t, fernTestValueTokenLifetime, obj.TokenLifetime)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitCreateIdpProvisioningSCIMTokenRequestContent(t *testing.T) {
	t.Run("SetTokenLifetime_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateIdpProvisioningSCIMTokenRequestContent{}
		var fernTestValueTokenLifetime *int

		// Act
		obj.SetTokenLifetime(fernTestValueTokenLifetime)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersListOrganizationDomainsRequestParameters(t *testing.T) {
	t.Run("SetFrom", func(t *testing.T) {
		obj := &ListOrganizationDomainsRequestParameters{}
		var fernTestValueFrom *string
		obj.SetFrom(fernTestValueFrom)
		assert.Equal(t, fernTestValueFrom, obj.From)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTake", func(t *testing.T) {
		obj := &ListOrganizationDomainsRequestParameters{}
		var fernTestValueTake *int
		obj.SetTake(fernTestValueTake)
		assert.Equal(t, fernTestValueTake, obj.Take)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitListOrganizationDomainsRequestParameters(t *testing.T) {
	t.Run("SetFrom_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListOrganizationDomainsRequestParameters{}
		var fernTestValueFrom *string

		// Act
		obj.SetFrom(fernTestValueFrom)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTake_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListOrganizationDomainsRequestParameters{}
		var fernTestValueTake *int

		// Act
		obj.SetTake(fernTestValueTake)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}
