// Code generated by Fern. DO NOT EDIT.

package domains

import (
	context "context"
	myorganization "github.com/auth0/myorganization-go"
	core "github.com/auth0/myorganization-go/core"
	internal "github.com/auth0/myorganization-go/internal"
	option "github.com/auth0/myorganization-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Add a domain to the identity provider's list of domains for [Home Realm Discovery (HRD)](https://auth0.com/docs/get-started/architecture-scenarios/business-to-business/authentication#home-realm-discovery). The domain passed must be claimed and verified by this organization.
func (c *Client) Create(
	ctx context.Context,
	idpID myorganization.IdpID,
	request *myorganization.CreateIdpDomainRequestContent,
	opts ...option.RequestOption,
) (*myorganization.CreateIdpDomainResponseContent, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		idpID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Remove a domain from an identity provider.
func (c *Client) Delete(
	ctx context.Context,
	idpID myorganization.IdpID,
	domain myorganization.OrgDomainName,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.Delete(
		ctx,
		idpID,
		domain,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}
