// Code generated by Fern. DO NOT EDIT.

package client

import (
	context "context"

	myorganization "github.com/auth0/myorganization-go"
	core "github.com/auth0/myorganization-go/core"
	internal "github.com/auth0/myorganization-go/internal"
	option "github.com/auth0/myorganization-go/option"
	identityproviders "github.com/auth0/myorganization-go/organization/configuration/identityproviders"
)

type Client struct {
	WithRawResponse   *RawClient
	IdentityProviders *identityproviders.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		IdentityProviders: identityproviders.NewClient(options),
		WithRawResponse:   NewRawClient(options),
		options:           options,
		baseURL:           options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Retrieve the My Organization API configuration. Returns only the `connection_deletion_behavior` and `allowed_strategies`. Identifier attributes such as `user_attribute_profile_id` and `connection_profile_id` are not included. Cache this information, as it does not change frequently.
func (c *Client) Get(
	ctx context.Context,
	opts ...option.RequestOption,
) (*myorganization.GetConfigurationResponseContent, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
