// Code generated by Fern. DO NOT EDIT.

package client

import (
	context "context"
	myorganization "github.com/auth0/myorganization-go"
	core "github.com/auth0/myorganization-go/core"
	internal "github.com/auth0/myorganization-go/internal"
	option "github.com/auth0/myorganization-go/option"
	apis "github.com/auth0/myorganization-go/organization/configuration/apis"
	identityproviders "github.com/auth0/myorganization-go/organization/configuration/identityproviders"
)

type Client struct {
	WithRawResponse   *RawClient
	APIs              *apis.Client
	IdentityProviders *identityproviders.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		APIs:              apis.NewClient(options),
		IdentityProviders: identityproviders.NewClient(options),
		WithRawResponse:   NewRawClient(options),
		options:           options,
		baseURL:           options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Retrieve the configuration for the /my-org API. This will return all stored client information with the exception of attributes that are identifiers. Identifier attributes will be given their own endpoint that will return the full object. This will give the components all of the information they will need to be successful. The SDK provider for the components should manage fetching and caching this information for all components.
func (c *Client) Get(
	ctx context.Context,
	opts ...option.RequestOption,
) (*myorganization.GetConfigurationResponseContent, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
