// Code generated by Fern. DO NOT EDIT.

package client

import (
	context "context"

	myorganization "github.com/auth0/myorganization-go"
	core "github.com/auth0/myorganization-go/core"
	internal "github.com/auth0/myorganization-go/internal"
	option "github.com/auth0/myorganization-go/option"
	scimtokens "github.com/auth0/myorganization-go/organization/identityproviders/provisioning/scimtokens"
)

type Client struct {
	WithRawResponse *RawClient
	SCIMTokens      *scimtokens.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		SCIMTokens:      scimtokens.NewClient(options),
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Retrieve the Provisioning Configuration for an Identity Provider specified by ID for this Organization.
func (c *Client) Get(
	ctx context.Context,
	idpID myorganization.IdpID,
	opts ...option.RequestOption,
) (*myorganization.GetIDPProvisioningConfigResponseContent, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		idpID,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Create a new Provisioning Configuration for an Identity Provider specified by ID for this Organization.
func (c *Client) Create(
	ctx context.Context,
	idpID myorganization.IdpID,
	opts ...option.RequestOption,
) (*myorganization.CreateIDPProvisioningConfigResponseContent, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		idpID,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Delete the Provisioning Configuration for an Identity Provider specified by ID for this Organization.
func (c *Client) Delete(
	ctx context.Context,
	idpID myorganization.IdpID,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.Delete(
		ctx,
		idpID,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// Refresh the attribute mapping for the Provisioning Configuration of an Identity Provider specified by ID for this Organization. Mappings are reset to the admin-defined defaults.
func (c *Client) UpdateAttributes(
	ctx context.Context,
	idpID myorganization.IdpID,
	request map[string]any,
	opts ...option.RequestOption,
) (*myorganization.GetIDPProvisioningConfigResponseContent, error) {
	response, err := c.WithRawResponse.UpdateAttributes(
		ctx,
		idpID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
