// Code generated by Fern. DO NOT EDIT.

package clients

import (
	context "context"
	myorganization "github.com/auth0/myorganization-go"
	core "github.com/auth0/myorganization-go/core"
	internal "github.com/auth0/myorganization-go/internal"
	option "github.com/auth0/myorganization-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Lists all API clients associated with the developer organization. Clients are used to obtain credentials for programmatic API access.
func (c *Client) List(
	ctx context.Context,
	opts ...option.RequestOption,
) (*myorganization.ListClientsResponseContent, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Create a new API client for the developer organization. The client can be used to obtain access tokens for calling tenant APIs.
func (c *Client) Create(
	ctx context.Context,
	request *myorganization.CreateClientRequestContent,
	opts ...option.RequestOption,
) (*myorganization.CreateClientResponseContent, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Delete an API client from the organization.
func (c *Client) Delete(
	ctx context.Context,
	// The ID of the client
	clientID myorganization.ClientID,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.Delete(
		ctx,
		clientID,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}
