// Code generated by Fern. DO NOT EDIT.

package verify

import (
	context "context"
	myorganization "github.com/auth0/myorganization-go"
	core "github.com/auth0/myorganization-go/core"
	internal "github.com/auth0/myorganization-go/internal"
	option "github.com/auth0/myorganization-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Get a verification text and start the domain verification process for a particular domain.
func (c *Client) Create(
	ctx context.Context,
	domainID myorganization.OrgDomainID,
	opts ...option.RequestOption,
) (myorganization.StartOrganizationDomainVerificationResponseContent, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		domainID,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
