// Code generated by Fern. DO NOT EDIT.

package client

import (
	core "github.com/auth0/myorganization-go/core"
	internal "github.com/auth0/myorganization-go/internal"
	client "github.com/auth0/myorganization-go/organization/configuration/client"
	domainsclient "github.com/auth0/myorganization-go/organization/domains/client"
	identityprovidersclient "github.com/auth0/myorganization-go/organization/identityproviders/client"
)

type Client struct {
	Configuration     *client.Client
	Domains           *domainsclient.Client
	IdentityProviders *identityprovidersclient.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		Configuration:     client.NewClient(options),
		Domains:           domainsclient.NewClient(options),
		IdentityProviders: identityprovidersclient.NewClient(options),
		options:           options,
		baseURL:           options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}
