// Code generated by Fern. DO NOT EDIT.

package client

import (
	core "github.com/auth0/myorganization-go/v2/core"
	internal "github.com/auth0/myorganization-go/v2/internal"
	client "github.com/auth0/myorganization-go/v2/organization/configuration/client"
	domainsclient "github.com/auth0/myorganization-go/v2/organization/domains/client"
	identityprovidersclient "github.com/auth0/myorganization-go/v2/organization/identityproviders/client"
	invitationsclient "github.com/auth0/myorganization-go/v2/organization/invitations/client"
	membersclient "github.com/auth0/myorganization-go/v2/organization/members/client"
	memberships "github.com/auth0/myorganization-go/v2/organization/memberships"
	roles "github.com/auth0/myorganization-go/v2/organization/roles"
	userstores "github.com/auth0/myorganization-go/v2/organization/userstores"
)

type Client struct {
	Configuration     *client.Client
	UserStores        *userstores.Client
	Domains           *domainsclient.Client
	IdentityProviders *identityprovidersclient.Client
	Members           *membersclient.Client
	Memberships       *memberships.Client
	Invitations       *invitationsclient.Client
	Roles             *roles.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		Configuration:     client.NewClient(options),
		UserStores:        userstores.NewClient(options),
		Domains:           domainsclient.NewClient(options),
		IdentityProviders: identityprovidersclient.NewClient(options),
		Members:           membersclient.NewClient(options),
		Memberships:       memberships.NewClient(options),
		Invitations:       invitationsclient.NewClient(options),
		Roles:             roles.NewClient(options),
		options:           options,
		baseURL:           options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}
