// Code generated by Fern. DO NOT EDIT.

package organization_invitations_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	myorganization "github.com/auth0/myorganization-go"
	client "github.com/auth0/myorganization-go/client"
	option "github.com/auth0/myorganization-go/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestOrganizationInvitationsListWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewWithOptions(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &myorganization.ListMemberInvitationsRequestParameters{
		Fields: myorganization.String(
			"fields",
		),
		IncludeFields: myorganization.Bool(
			true,
		),
		From: myorganization.String(
			"from",
		),
		Take: myorganization.Int(
			1,
		),
		Sort: myorganization.String(
			"sort",
		),
	}
	_, invocationErr := client.Organization.Invitations.List(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestOrganizationInvitationsListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestOrganizationInvitationsListWithWireMock", "GET", "/member-invitations", map[string]string{"fields": "fields", "include_fields": "true", "from": "from", "take": "1", "sort": "sort"}, 1)
}

func TestOrganizationInvitationsCreateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewWithOptions(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &myorganization.CreateMemberInvitationRequestContent{
		Invitees: []*myorganization.CreateMemberInvitationInvitee{
			&myorganization.CreateMemberInvitationInvitee{
				Email: "user@example.com",
				Roles: []myorganization.RoleID{
					"rol_0000000000000001",
				},
			},
		},
		Inviter: &myorganization.MemberInvitationInviter{
			Name: myorganization.String(
				"Allison the Admin",
			),
		},
		IdentityProviderID: myorganization.String(
			"con_2CZPv6IY0gWzDaQJ",
		),
		TTLSec: myorganization.Int(
			3600,
		),
	}
	_, invocationErr := client.Organization.Invitations.Create(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestOrganizationInvitationsCreateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestOrganizationInvitationsCreateWithWireMock", "POST", "/member-invitations", nil, 1)
}

func TestOrganizationInvitationsGetWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewWithOptions(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &myorganization.GetMemberInvitationRequestParameters{
		Fields: myorganization.String(
			"fields",
		),
		IncludeFields: myorganization.Bool(
			true,
		),
	}
	_, invocationErr := client.Organization.Invitations.Get(
		context.TODO(),
		"invitation_id",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestOrganizationInvitationsGetWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestOrganizationInvitationsGetWithWireMock", "GET", "/member-invitations/invitation_id", map[string]string{"fields": "fields", "include_fields": "true"}, 1)
}

func TestOrganizationInvitationsDeleteWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewWithOptions(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	invocationErr := client.Organization.Invitations.Delete(
		context.TODO(),
		"invitation_id",
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestOrganizationInvitationsDeleteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestOrganizationInvitationsDeleteWithWireMock", "DELETE", "/member-invitations/invitation_id", nil, 1)
}
