// Code generated by Fern. DO NOT EDIT.

package memberships

import (
	context "context"

	myorganization "github.com/auth0/myorganization-go"
	core "github.com/auth0/myorganization-go/core"
	internal "github.com/auth0/myorganization-go/internal"
	option "github.com/auth0/myorganization-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Remove one member from this Organization. The underlying user account is not deleted.
func (c *Client) DeleteMemberships(
	ctx context.Context,
	request *myorganization.DeleteOrganizationMembershipsRequestParameters,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.DeleteMemberships(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}
