// Code generated by Fern. DO NOT EDIT.

package scimtokens

import (
	context "context"
	myorganization "github.com/auth0/myorganization-go"
	core "github.com/auth0/myorganization-go/core"
	internal "github.com/auth0/myorganization-go/internal"
	option "github.com/auth0/myorganization-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// List the Provisioning SCIM tokens for this identity provider.
func (c *Client) List(
	ctx context.Context,
	idpID myorganization.IdpID,
	opts ...option.RequestOption,
) (*myorganization.ListIdpProvisioningSCIMTokensResponseContent, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		idpID,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Create a Provisioning SCIM token for this identity provider.
func (c *Client) Create(
	ctx context.Context,
	idpID myorganization.IdpID,
	request *myorganization.CreateIdpProvisioningSCIMTokenRequestContent,
	opts ...option.RequestOption,
) (myorganization.CreateIdpProvisioningSCIMTokenResponseContent, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		idpID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Delete a Provisioning SCIM configuration for an identity provider.
func (c *Client) Delete(
	ctx context.Context,
	idpID myorganization.IdpID,
	idpSCIMTokenID myorganization.IdpProvisioningSCIMTokenID,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.Delete(
		ctx,
		idpID,
		idpSCIMTokenID,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}
