// Code generated by Fern. DO NOT EDIT.

package client

import (
	context "context"
	myorganization "github.com/auth0/myorganization-go"
	core "github.com/auth0/myorganization-go/core"
	internal "github.com/auth0/myorganization-go/internal"
	option "github.com/auth0/myorganization-go/option"
	domains "github.com/auth0/myorganization-go/organization/identityproviders/domains"
	client "github.com/auth0/myorganization-go/organization/identityproviders/provisioning/client"
)

type Client struct {
	WithRawResponse *RawClient
	Domains         *domains.Client
	Provisioning    *client.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		Domains:         domains.NewClient(options),
		Provisioning:    client.NewClient(options),
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// List the identity providers associated with this organization.
func (c *Client) List(
	ctx context.Context,
	opts ...option.RequestOption,
) (*myorganization.ListIdentityProvidersResponseContent, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Create an identity provider associated with this organization.
func (c *Client) Create(
	ctx context.Context,
	request myorganization.CreateIdentityProviderRequestContent,
	opts ...option.RequestOption,
) (myorganization.CreateIdentityProviderResponseContent, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve the details for one particular identity-provider.
func (c *Client) Get(
	ctx context.Context,
	idpID myorganization.IdpID,
	opts ...option.RequestOption,
) (myorganization.GetIdentityProviderResponseContent, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		idpID,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Delete an identity provider from this organization.
func (c *Client) Delete(
	ctx context.Context,
	idpID myorganization.IdpID,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.Delete(
		ctx,
		idpID,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// Update an identity provider associated with this organization.
func (c *Client) Update(
	ctx context.Context,
	idpID myorganization.IdpID,
	request myorganization.UpdateIdentityProviderRequestContent,
	opts ...option.RequestOption,
) (myorganization.UpdateIdentityProviderResponseContent, error) {
	response, err := c.WithRawResponse.Update(
		ctx,
		idpID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Triggers a refresh of attribute mappings on the identity provider by overriding it with the admin defined defaults. The endpoint doesn't accept any body parameters.
func (c *Client) UpdateAttributes(
	ctx context.Context,
	idpID myorganization.IdpID,
	request map[string]any,
	opts ...option.RequestOption,
) (myorganization.GetIdentityProviderResponseContent, error) {
	response, err := c.WithRawResponse.UpdateAttributes(
		ctx,
		idpID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Delete underlying identity provider from this organization.
func (c *Client) Detach(
	ctx context.Context,
	idpID myorganization.IdpID,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.Detach(
		ctx,
		idpID,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}
