// Code generated by Fern. DO NOT EDIT.

package organization_identity_providers_provisioning_scim_tokens_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	myorganization "github.com/auth0/myorganization-go"
	client "github.com/auth0/myorganization-go/client"
	option "github.com/auth0/myorganization-go/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestOrganizationIdentityProvidersProvisioningSCIMTokensListWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewWithOptions(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	_, invocationErr := client.Organization.IdentityProviders.Provisioning.SCIMTokens.List(
		context.TODO(),
		"idp_id",
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestOrganizationIdentityProvidersProvisioningSCIMTokensListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestOrganizationIdentityProvidersProvisioningSCIMTokensListWithWireMock", "GET", "/identity-providers/idp_id/provisioning/scim-tokens", nil, 1)
}

func TestOrganizationIdentityProvidersProvisioningSCIMTokensCreateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewWithOptions(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &myorganization.CreateIdpProvisioningSCIMTokenRequestContent{
		TokenLifetime: myorganization.Int(
			86400,
		),
	}
	_, invocationErr := client.Organization.IdentityProviders.Provisioning.SCIMTokens.Create(
		context.TODO(),
		"idp_id",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestOrganizationIdentityProvidersProvisioningSCIMTokensCreateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestOrganizationIdentityProvidersProvisioningSCIMTokensCreateWithWireMock", "POST", "/identity-providers/idp_id/provisioning/scim-tokens", nil, 1)
}

func TestOrganizationIdentityProvidersProvisioningSCIMTokensDeleteWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewWithOptions(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	invocationErr := client.Organization.IdentityProviders.Provisioning.SCIMTokens.Delete(
		context.TODO(),
		"idp_id",
		"idp_scim_token_id",
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestOrganizationIdentityProvidersProvisioningSCIMTokensDeleteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestOrganizationIdentityProvidersProvisioningSCIMTokensDeleteWithWireMock", "DELETE", "/identity-providers/idp_id/provisioning/scim-tokens/idp_scim_token_id", nil, 1)
}
