// Code generated by Fern. DO NOT EDIT.

package invitations

import (
	context "context"
	http "net/http"

	myorganization "github.com/auth0/myorganization-go"
	core "github.com/auth0/myorganization-go/core"
	internal "github.com/auth0/myorganization-go/internal"
	option "github.com/auth0/myorganization-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Retrieve a list of all member invitations for this Organization.
func (c *Client) List(
	ctx context.Context,
	request *myorganization.ListMemberInvitationsRequestParameters,
	opts ...option.RequestOption,
) (*core.Page[*string, *myorganization.MemberInvitation, *myorganization.ListMembersInvitationsResponseContent], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"https://%7BTENANT%7D.auth0.com/my-org/v1",
	)
	endpointURL := baseURL + "/member-invitations"
	queryParams, err := internal.QueryValuesWithDefaults(
		request,
		map[string]any{
			"include_fields": true,
			"take":           50,
			"sort":           "created_at:-1",
		},
	)
	if err != nil {
		return nil, err
	}
	headers := internal.MergeHeaders(
		c.options.ToHeader(),
		options.ToHeader(),
	)
	prepareCall := func(pageRequest *core.PageRequest[*string]) *internal.CallParams {
		if pageRequest.Cursor != nil {
			queryParams.Set("from", *pageRequest.Cursor)
		}
		nextURL := endpointURL
		if len(queryParams) > 0 {
			nextURL += "?" + queryParams.Encode()
		}
		return &internal.CallParams{
			URL:             nextURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        pageRequest.Response,
			ErrorDecoder:    internal.NewErrorDecoder(myorganization.ErrorCodes),
		}
	}
	readPageResponse := func(response *myorganization.ListMembersInvitationsResponseContent) *core.PageResponse[*string, *myorganization.MemberInvitation, *myorganization.ListMembersInvitationsResponseContent] {
		var zeroValue *string
		next := response.Next
		results := response.Invitations
		return &core.PageResponse[*string, *myorganization.MemberInvitation, *myorganization.ListMembersInvitationsResponseContent]{
			Results:  results,
			Response: response,
			Next:     next,
			Done:     next == zeroValue,
		}
	}
	pager := internal.NewCursorPager(
		c.caller,
		prepareCall,
		readPageResponse,
	)
	return pager.GetPage(ctx, request.From)
}

// Create one or more member invitations for this Organization. If an active invitation already exists for a user, generating a new invitation will automatically revoke any outstanding invitations for that user. Roles specified in the payload will be granted to the user upon acceptance of the invitation.
func (c *Client) Create(
	ctx context.Context,
	request *myorganization.CreateMemberInvitationRequestContent,
	opts ...option.RequestOption,
) (myorganization.CreateMemberInvitationResponseContent, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve details of a member invitation specified by ID for this Organization.
func (c *Client) Get(
	ctx context.Context,
	invitationID myorganization.InvitationID,
	request *myorganization.GetMemberInvitationRequestParameters,
	opts ...option.RequestOption,
) (myorganization.GetMemberInvitationResponseContent, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		invitationID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Revoke a member invitation specified by ID for this Organization.
func (c *Client) Delete(
	ctx context.Context,
	invitationID myorganization.InvitationID,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.Delete(
		ctx,
		invitationID,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}
