// Code generated by Fern. DO NOT EDIT.

package client

import (
	context "context"
	myorganization "github.com/auth0/myorganization-go"
	core "github.com/auth0/myorganization-go/core"
	internal "github.com/auth0/myorganization-go/internal"
	option "github.com/auth0/myorganization-go/option"
	identityproviders "github.com/auth0/myorganization-go/organization/domains/identityproviders"
	verify "github.com/auth0/myorganization-go/organization/domains/verify"
	http "net/http"
)

type Client struct {
	WithRawResponse   *RawClient
	Verify            *verify.Client
	IdentityProviders *identityproviders.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		Verify:            verify.NewClient(options),
		IdentityProviders: identityproviders.NewClient(options),
		WithRawResponse:   NewRawClient(options),
		options:           options,
		baseURL:           options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Retrieve a list of all pending and verified domains for this Organization.
func (c *Client) List(
	ctx context.Context,
	request *myorganization.ListOrganizationDomainsRequestParameters,
	opts ...option.RequestOption,
) (*core.Page[*string, *myorganization.OrgDomain, *myorganization.ListOrganizationDomainsResponseContent], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"https://%7BTENANT%7D.auth0.com/my-org",
	)
	endpointURL := baseURL + "/domains"
	queryParams, err := internal.QueryValuesWithDefaults(
		request,
		map[string]any{
			"take": 50,
		},
	)
	if err != nil {
		return nil, err
	}
	headers := internal.MergeHeaders(
		c.options.ToHeader(),
		options.ToHeader(),
	)
	prepareCall := func(pageRequest *core.PageRequest[*string]) *internal.CallParams {
		if pageRequest.Cursor != nil {
			queryParams.Set("from", *pageRequest.Cursor)
		}
		nextURL := endpointURL
		if len(queryParams) > 0 {
			nextURL += "?" + queryParams.Encode()
		}
		return &internal.CallParams{
			URL:             nextURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        pageRequest.Response,
			ErrorDecoder:    internal.NewErrorDecoder(myorganization.ErrorCodes),
		}
	}
	readPageResponse := func(response *myorganization.ListOrganizationDomainsResponseContent) *core.PageResponse[*string, *myorganization.OrgDomain, *myorganization.ListOrganizationDomainsResponseContent] {
		var zeroValue *string
		next := response.Next
		results := response.OrganizationDomains
		return &core.PageResponse[*string, *myorganization.OrgDomain, *myorganization.ListOrganizationDomainsResponseContent]{
			Results:  results,
			Response: response,
			Next:     next,
			Done:     next == zeroValue,
		}
	}
	pager := internal.NewCursorPager(
		c.caller,
		prepareCall,
		readPageResponse,
	)
	return pager.GetPage(ctx, request.From)
}

// Create a new domain for this Organization.
func (c *Client) Create(
	ctx context.Context,
	request *myorganization.CreateOrganizationDomainRequestContent,
	opts ...option.RequestOption,
) (myorganization.CreateOrganizationDomainResponseContent, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve details of a domain specified by ID for this Organization.
func (c *Client) Get(
	ctx context.Context,
	domainID myorganization.OrgDomainID,
	opts ...option.RequestOption,
) (myorganization.GetOrganizationDomainResponseContent, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		domainID,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Remove a domain specified by ID from this Organization.
func (c *Client) Delete(
	ctx context.Context,
	domainID myorganization.OrgDomainID,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.Delete(
		ctx,
		domainID,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}
