// Code generated by Fern. DO NOT EDIT.

package client

import (
	context "context"
	myorganization "github.com/auth0/myorganization-go"
	core "github.com/auth0/myorganization-go/core"
	internal "github.com/auth0/myorganization-go/internal"
	option "github.com/auth0/myorganization-go/option"
	identityproviders "github.com/auth0/myorganization-go/organization/domains/identityproviders"
	verify "github.com/auth0/myorganization-go/organization/domains/verify"
)

type Client struct {
	WithRawResponse   *RawClient
	Verify            *verify.Client
	IdentityProviders *identityproviders.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		Verify:            verify.NewClient(options),
		IdentityProviders: identityproviders.NewClient(options),
		WithRawResponse:   NewRawClient(options),
		options:           options,
		baseURL:           options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Lists all domains pending and verified for an organization.
func (c *Client) List(
	ctx context.Context,
	opts ...option.RequestOption,
) (*myorganization.ListOrganizationDomainsResponseContent, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Create a new domain for an organization.
func (c *Client) Create(
	ctx context.Context,
	request *myorganization.CreateOrganizationDomainRequestContent,
	opts ...option.RequestOption,
) (myorganization.CreateOrganizationDomainResponseContent, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve a domain for an organization.
func (c *Client) Get(
	ctx context.Context,
	domainID myorganization.OrgDomainID,
	opts ...option.RequestOption,
) (myorganization.GetOrganizationDomainResponseContent, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		domainID,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Remove a domain from this organization.
func (c *Client) Delete(
	ctx context.Context,
	domainID myorganization.OrgDomainID,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.Delete(
		ctx,
		domainID,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}
