// Code generated by Fern. DO NOT EDIT.

package roles

import (
	context "context"

	myorganization "github.com/auth0/myorganization-go/v2"
	core "github.com/auth0/myorganization-go/v2/core"
	internal "github.com/auth0/myorganization-go/v2/internal"
	option "github.com/auth0/myorganization-go/v2/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Retrieve the roles assigned to a member invitation specified by ID for this Organization.
func (c *Client) List(
	ctx context.Context,
	invitationID myorganization.InvitationID,
	opts ...option.RequestOption,
) (*myorganization.GetMemberInvitationRolesResponseContent, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		invitationID,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
