// Code generated by Fern. DO NOT EDIT.

package roles

import (
	context "context"
	http "net/http"

	myorganization "github.com/auth0/myorganization-go/v2"
	core "github.com/auth0/myorganization-go/v2/core"
	internal "github.com/auth0/myorganization-go/v2/internal"
	option "github.com/auth0/myorganization-go/v2/option"
	invitations "github.com/auth0/myorganization-go/v2/organization/invitations"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (r *RawClient) List(
	ctx context.Context,
	invitationID myorganization.InvitationID,
	opts ...option.RequestOption,
) (*core.Response[*myorganization.GetMemberInvitationRolesResponseContent], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://%7BTENANT%7D.auth0.com/my-org/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/member-invitations/%v/roles",
		invitationID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *myorganization.GetMemberInvitationRolesResponseContent
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(invitations.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*myorganization.GetMemberInvitationRolesResponseContent]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
